---
title: "Analysis"
# date automatically set to today
date: "`r Sys.Date()`"
# see ./_quarto.yml to change other options
# (e.g., author, rendering format (pdf by default), ...)
# these options apply to all .qmd files in the project 
---

```{r}
#| label: setup

# load packages; hide startup messages for pretty output
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(modelsummary))

# load functions
source("./src/lib/io.R")

# read data; we know the column types, so we can suppress the messages
df <- read_csv("./data/processed/data.csv", show_col_types = FALSE)
```

```{r}
#| label: analysis

models <- list(
  lm(exam_score ~ previous_scores, data = df),
  lm(exam_score ~ hours_studied + sleep_hours + attendance_percent + previous_scores, data = df)
)
```

```{r}
#| label: tbl-table
#| tbl-cap: Regression of Exam Scores on Study Inputs

m <- modelsummary(models, output = "tinytable")
m # show the table in the quarto report
# save the table to ./assets/tables/table.tex for use in .tex files
# see ./src/lib/io.R for documentation
save_table(m, "table")
```

```{r}
#| label: fig-figure
#| fig-cap: Coefficient Estimates with Confidence Intervals

modelplot(models)
# save the figure to ./assets/figures/figure.pdf for use in .tex files
# see ./src/lib/io.R for documentation
save_figure("figure")
```
